AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB GSI Multi-Attribute Key Demo

Parameters:
  StudentId:
    Type: String
    Default: instructor
    Description: Student ID for unique resource naming

Resources:
  OrdersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'Orders-GSI-Demo-${StudentId}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: order_id
          AttributeType: S
        - AttributeName: customer_id
          AttributeType: S
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: order_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: CustomerStatusIndex
          KeySchema:
            - AttributeName: customer_id
              KeyType: HASH
            - AttributeName: status
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

Outputs:
  TableName:
    Description: DynamoDB Table Name
    Value: !Ref OrdersTable
  TableArn:
    Description: DynamoDB Table ARN
    Value: !GetAtt OrdersTable.Arn
