AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  Lambda Durable Functions - Order Processing Demo
  2025年12月 GA の新機能。Step Functions を使わずにコードファーストでワークフローを構築。

Parameters:
  StudentId:
    Type: String
    Default: instructor
    Description: 受講生ID（リソース名の一意性確保用）

Resources:
  OrderProcessingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub order-processing-durable-${StudentId}
      Runtime: python3.12
      Handler: app.lambda_handler
      Timeout: 900
      MemorySize: 256
      # Durable Functions 設定（2025年12月 GA）
      # 参考: https://docs.aws.amazon.com/lambda/latest/dg/durable-functions.html
      DurableConfig:
        ExecutionTimeout: 86400        # 最大実行時間（秒）: 1日 = 86400秒
        RetentionPeriodInDays: 7       # 実行履歴保持期間: 7日間
      Policies:
        - CloudWatchLogsFullAccess

Outputs:
  FunctionName:
    Description: Lambda Function Name
    Value: !Ref OrderProcessingFunction
  FunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt OrderProcessingFunction.Arn
  StudentId:
    Description: Student ID used for resource naming
    Value: !Ref StudentId
